"""add refresh token hash to users

Revision ID: df596d92900f
Revises: 3fc2409d7125
Create Date: 2026-02-09 22:38:49.425058

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'df596d92900f'
down_revision: Union[str, Sequence[str], None] = '3fc2409d7125'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_mcp_audit_logs_operation'), table_name='mcp_audit_logs')
    op.drop_index(op.f('ix_mcp_audit_logs_table_name'), table_name='mcp_audit_logs')
    op.drop_index(op.f('ix_mcp_audit_logs_user_id'), table_name='mcp_audit_logs')
    op.drop_table('mcp_audit_logs')
    op.add_column('users', sa.Column('refresh_token_hash', sa.String(length=255), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'refresh_token_hash')
    op.create_table('mcp_audit_logs',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('user_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('operation', sa.VARCHAR(length=16), autoincrement=False, nullable=False),
    sa.Column('table_name', sa.VARCHAR(length=128), autoincrement=False, nullable=False),
    sa.Column('sql_text', sa.TEXT(), autoincrement=False, nullable=False),
    sa.Column('status', sa.VARCHAR(length=32), autoincrement=False, nullable=False),
    sa.Column('created_at', postgresql.TIMESTAMP(timezone=True), autoincrement=False, nullable=False),
    sa.PrimaryKeyConstraint('id', name=op.f('mcp_audit_logs_pkey'))
    )
    op.create_index(op.f('ix_mcp_audit_logs_user_id'), 'mcp_audit_logs', ['user_id'], unique=False)
    op.create_index(op.f('ix_mcp_audit_logs_table_name'), 'mcp_audit_logs', ['table_name'], unique=False)
    op.create_index(op.f('ix_mcp_audit_logs_operation'), 'mcp_audit_logs', ['operation'], unique=False)
    # ### end Alembic commands ###
